# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CS256-project/nexys-a7-100t-master.xdc

# IP: ip/enemy1_sprite/enemy1_sprite.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==enemy1_sprite || ORIG_REF_NAME==enemy1_sprite} -quiet] -quiet

# IP: ip/bullet_sprite/bullet_sprite.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bullet_sprite || ORIG_REF_NAME==bullet_sprite} -quiet] -quiet

# IP: ip/cannon_sprite/cannon_sprite.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cannon_sprite || ORIG_REF_NAME==cannon_sprite} -quiet] -quiet

# IP: ip/background_sprite/background_sprite.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==background_sprite || ORIG_REF_NAME==background_sprite} -quiet] -quiet

# XDC: /rhome/forystmj/CS256-project/CS256-project.gen/sources_1/ip/enemy1_sprite/enemy1_sprite_ooc.xdc

# XDC: /rhome/forystmj/CS256-project/CS256-project.gen/sources_1/ip/bullet_sprite/bullet_sprite_ooc.xdc

# XDC: /rhome/forystmj/CS256-project/CS256-project.gen/sources_1/ip/cannon_sprite/cannon_sprite_ooc.xdc

# XDC: /rhome/forystmj/CS256-project/CS256-project.gen/sources_1/ip/background_sprite/background_sprite_ooc.xdc
