webtalk_init -webtalk_dir /rhome/forystmj/CS256-project/CS256-project.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 30 17:22:24 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887999_1777552194_210720986_228" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "43ba7f63-bead-4bd6-b00e-3e4f49dbdfd4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d7a26307a0184a7abc15319d2fb51215" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 9534 64-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1500.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "1622.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126832_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2184653855 -regid "211887999_1777552194_210720986_228" -xml /rhome/forystmj/CS256-project/CS256-project.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /rhome/forystmj/CS256-project/CS256-project.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /rhome/forystmj/CS256-project/CS256-project.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
